ifndef CRYPTECH_ROOT
  CRYPTECH_ROOT := $(abspath ../../../../..)
endif

TFMDIR := $(abspath ../../libtfm)

vpath %.c ${CRYPTECH_ROOT}/sw/libhal/utils
vpath %.h ${CRYPTECH_ROOT}/sw/libhal/utils:${LIBTFM_DIR}

include ${CRYPTECH_ROOT}/sw/libhal/utils/GNUmakefile
